export const FETCH_POSTS = "FETCH_POSTS";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_ERROR = "FETCH_POSTS_ERROR";

export const MOVE_UP_POST = "MOVE_UP_POST";
export const MOVE_DOWN_POST = "MOVE_DOWN_POST";

export const ADD_TO_ACTION_STACK = "ADD_TO_ACTION_STACK";
export const SET_TIME_TRAVELING = "SET_TIME_TRAVELING";
export const TIME_TRAVEL_TO_ACTION = "TIME_TRAVEL_TO_ACTION";
